/**                                                                                                                                                                                                               
  * Login Component                                                                                                                                                                                                
  *                                                                                                                                                                                                                
  * Provides WebAuthn-based authentication for the FormFillVoiceAI application.                                                                                                                                    
  */                                                                                                                                                                                                               
                                                                                                                                                                                                                   
class Login {                                                                                                                                                                                                     
    constructor() {                                                                                                                                                                                                 
      this.container = null;                                                                                                                                                                                        
      this.isAuthenticated = false;                                                                                                                                                                                 
      this.credential = null;                                                                                                                                                                                       
      this.userId = `user-${Date.now()}`;                                                                                                                                                                           
    }                                                                                                                                                                                                               
                                                                                                                                                                                                                    
    /**                                                                                                                                                                                                             
     * Initialize the login component                                                                                                                                                                               
     * @param {HTMLElement} container - Container element to render the login UI                                                                                                                                    
     */                                                                                                                                                                                                             
    async initialize(container) {                                                                                                                                                                                   
      this.container = container;                                                                                                                                                                                   
                                                                                                                                                                                                                    
      // Check if we have a stored credential                                                                                                                                                                       
      const storedCredential = localStorage.getItem('webauthn-credential');                                                                                                                                         
      if (storedCredential) {                                                                                                                                                                                       
        this.credential = JSON.parse(storedCredential);                                                                                                                                                             
      }                                                                                                                                                                                                             
                                                                                                                                                                                                                    
      this.render();                                                                                                                                                                                                
    }                                                                                                                                                                                                               
                                                                                                                                                                                                                    
    /**                                                                                                                                                                                                             
     * Render the login UI                                                                                                                                                                                          
     */                                                                                                                                                                                                             
    render() {                                                                                                                                                                                                      
      if (!this.container) return;                                                                                                                                                                                  
                                                                                                                                                                                                                    
      this.container.innerHTML = `                                                                                                                                                                                  
        <div class="login-container">                                                                                                                                                                               
          <h2>Secure Authentication</h2>                                                                                                                                                                            
          <p>Use WebAuthn for secure, hardware-backed authentication</p>                                                                                                                                            
                                                                                                                                                                                                                    
          <div class="login-buttons">                                                                                                                                                                               
            ${!this.credential ?                                                                                                                                                                                    
              `<button id="register-button" class="primary-button">Register New Device</button>` :                                                                                                                  
              `<button id="login-button" class="primary-button">Login with WebAuthn</button>`                                                                                                                       
            }                                                                                                                                                                                                       
          </div>                                                                                                                                                                                                    
                                                                                                                                                                                                                    
          <div id="login-status" class="status-message"></div>                                                                                                                                                      
        </div>                                                                                                                                                                                                      
      `;                                                                                                                                                                                                            
                                                                                                                                                                                                                    
      // Add event listeners                                                                                                                                                                                        
      if (!this.credential) {                                                                                                                                                                                       
        const registerButton = this.container.querySelector('#register-button');                                                                                                                                    
        if (registerButton) {                                                                                                                                                                                       
          registerButton.addEventListener('click', () => this.register());                                                                                                                                          
        }                                                                                                                                                                                                           
      } else {                                                                                                                                                                                                      
        const loginButton = this.container.querySelector('#login-button');                                                                                                                                          
        if (loginButton) {                                                                                                                                                                                          
          loginButton.addEventListener('click', () => this.authenticate());                                                                                                                                         
        }                                                                                                                                                                                                           
      }                                                                                                                                                                                                             
    }                                                                                                                                                                                                               
                                                                                                                                                                                                                    
    /**                                                                                                                                                                                                             
     * Register a new WebAuthn credential                                                                                                                                                                           
     */                                                                                                                                                                                                             
    async register() {                                                                                                                                                                                              
      const statusElement = this.container.querySelector('#login-status');                                                                                                                                          
      statusElement.textContent = 'Registering...';                                                                                                                                                                 
                                                                                                                                                                                                                    
      try {                                                                                                                                                                                                         
        // Call the WebAuthn registration API                                                                                                                                                                       
        const result = await window.api.registerWebAuthn(this.userId);                                                                                                                                              
                                                                                                                                                                                                                    
        if (result.success) {                                                                                                                                                                                       
          // Store the credential                                                                                                                                                                                   
          this.credential = result.credential;                                                                                                                                                                      
          localStorage.setItem('webauthn-credential', JSON.stringify(result.credential));                                                                                                                           
                                                                                                                                                                                                                    
          statusElement.textContent = 'Registration successful!';                                                                                                                                                   
                                                                                                                                                                                                                    
          // Update the UI                                                                                                                                                                                          
          setTimeout(() => this.render(), 1000);                                                                                                                                                                    
        } else {                                                                                                                                                                                                    
          statusElement.textContent = `Registration failed: ${result.error}`;                                                                                                                                       
        }                                                                                                                                                                                                           
      } catch (error) {                                                                                                                                                                                             
        console.error('Registration error:', error);                                                                                                                                                                
        statusElement.textContent = `Error: ${error.message}`;                                                                                                                                                      
      }                                                                                                                                                                                                             
    }                                                                                                                                                                                                               
                                                                                                                                                                                                                    
    /**                                                                                                                                                                                                             
     * Authenticate using WebAuthn                                                                                                                                                                                  
     */                                                                                                                                                                                                             
    async authenticate() {                                                                                                                                                                                          
      const statusElement = this.container.querySelector('#login-status');                                                                                                                                          
      statusElement.textContent = 'Authenticating...';                                                                                                                                                              
                                                                                                                                                                                                                    
      try {                                                                                                                                                                                                         
        // Call the WebAuthn authentication API                                                                                                                                                                     
        const result = await window.api.authenticateWebAuthn(this.credential);                                                                                                                                      
                                                                                                                                                                                                                    
        if (result.success) {                                                                                                                                                                                       
          this.isAuthenticated = true;                                                                                                                                                                              
          statusElement.textContent = 'Authentication successful!';                                                                                                                                                 
                                                                                                                                                                                                                    
          // Trigger the authenticated event                                                                                                                                                                        
          const event = new CustomEvent('login-authenticated', {                                                                                                                                                    
            detail: { userId: this.userId }                                                                                                                                                                         
          });                                                                                                                                                                                                       
          this.container.dispatchEvent(event);                                                                                                                                                                      
        } else {                                                                                                                                                                                                    
          statusElement.textContent = `Authentication failed: ${result.error}`;                                                                                                                                     
        }                                                                                                                                                                                                           
      } catch (error) {                                                                                                                                                                                             
        console.error('Authentication error:', error);                                                                                                                                                              
        statusElement.textContent = `Error: ${error.message}`;                                                                                                                                                      
      }                                                                                                                                                                                                             
    }                                                                                                                                                                                                               
                                                                                                                                                                                                                    
    /**                                                                                                                                                                                                             
     * Check if the user is authenticated                                                                                                                                                                           
     * @returns {boolean} - Whether the user is authenticated                                                                                                                                                       
     */                                                                                                                                                                                                             
    isUserAuthenticated() {                                                                                                                                                                                         
      return this.isAuthenticated;                                                                                                                                                                                  
    }                                                                                                                                                                                                               
                                                                                                                                                                                                                    
    /**                                                                                                                                                                                                             
     * Get the user ID                                                                                                                                                                                              
     * @returns {string} - The user ID                                                                                                                                                                              
     */                                                                                                                                                                                                             
    getUserId() {                                                                                                                                                                                                   
      return this.userId;                                                                                                                                                                                           
    }                                                                                                                                                                                                               
  }                                                                                                                                                                                                                 
                                                                                                                                                                                                                    
  export default Login;  